name: sqlite3_connection_pool
description: High-performance async connection pool for SQLite on native platforms.
version: 0.1.0
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_connection_pool
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues
resolution: workspace

environment:
  sdk: ^3.10.0

topics:
  - sql
  - database
  - ffi
  - sqlite

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.2.0
  hooks: ^1.0.0
  meta: ^1.17.0
  sqlite3: ^3.1.6-wip

dev_dependencies:
  lints: ^6.1.0
  ffigen: ^20.1.1
  logging: ^1.3.0
  test: ^1.29.0
  test_descriptor: ^2.0.2
  path: ^1.9.1
