name: sqlite3_connection_pool
description: High-performance low-level async connection pool for SQLite on native platforms.
version: 0.0.1
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_connection_pool
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues
resolution: workspace

environment:
  sdk: ^3.10.0

topics:
  - sql
  - database
  - ffi
  - sqlite

dependencies:
  ffi: ^2.2.0
  meta: ^1.18.1
  sqlite3: ^3.1.5

dev_dependencies:
  lints: ^6.1.0
  ffigen: ^20.1.1
  logging: ^1.3.0

