name: custom_extension
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  sqlite3:

  code_assets: ^1.0.0
  hooks: ^1.0.0
  http: ^1.5.0
  tar: ^2.0.0

dev_dependencies:
  test: ^1.26.0
