name: sqlite3_native_assets
description: Access to SQLite with the `sqlite3` package and the upcoming "Native assets" feature. This package will eventually replace `sqlite3_flutter_libs`.
version: 0.0.3
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_native_assets
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: ^3.7.0

dependencies:
  sqlite3: ^2.7.4
  native_assets_cli: ^0.14.0
  native_toolchain_c: ^0.11.0
  logging: ^1.3.0
  http: ^1.3.0
  archive: ^4.0.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  sqlite3:
    path: ../sqlite3/
