name: sqlite3_web
description: Utilities to simplify accessing sqlite3 on the web, with automated feature detection.
version: 0.1.2-wip
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_web
repository: https://github.com/simolus3/sqlite3.dart

environment:
  sdk: ^3.3.0

dependencies:
  sqlite3: ^2.4.3
  stream_channel: ^2.1.2
  web: ^1.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.5
  build_web_compilers: ^4.0.9
  build_runner: ^2.4.8
  build_daemon: ^4.0.2
  webdriver: ^3.0.3
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  package_config: ^2.1.0
  path: ^1.9.0
  collection: ^1.18.0
  async: ^2.11.0

dependency_overrides:
  sqlite3:
    path: ../sqlite3/
