name: flutter_libs
description: Integration tests for the sqlite3_flutter_libs package

publish_to: 'none'
version: 1.0.0+1

flutter:
  disable-swift-package-manager: true

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  sqlite3_flutter_libs:
    path: ../../sqlite3_flutter_libs
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  sqlite3:
    path: ../../sqlite3
  test: ^1.18.0
