name: pkg_sqlite3_examples_workspace
publish_to: none

environment:
  sdk: ^3.10.0-0

workspace:
  - flutter_integration_tests
  - multiplatform

dependency_overrides:
  sqlite3:
    path: ../sqlite3
  sqlite3_connection_pool:
    path: ../sqlite3_connection_pool
