name: sqlite3_flutter_libs
description: Flutter plugin to include native sqlite3 libraries with your app
version: 0.5.27
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_flutter_libs
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: eu.simonbinder.sqlite3_flutter_libs
        pluginClass: Sqlite3FlutterLibsPlugin
      ios:
        pluginClass: Sqlite3FlutterLibsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: Sqlite3FlutterLibsPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: Sqlite3FlutterLibsPlugin
      windows:
        pluginClass: Sqlite3FlutterLibsPlugin
