name: sqlite3
description: Provides lightweight yet convenient bindings to SQLite by using dart:ffi
version: 1.11.1
homepage: https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  ffi: '>=1.2.1 <3.0.0'
  js: ^0.6.4
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.0.0
  ffigen: ^6.0.0
  http: ^0.13.4
  lints: ^2.0.1
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  stream_channel: ^2.1.0
  test: ^1.17.0
  test_descriptor: ^2.0.0
